version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: movies-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local